import { GameMode, VehicleData } from '../types/vehicle';

// Generated by tools/build_vehicle_db.py from the unpacked game files.
export interface GameVehicle {
  short: string;
  country: string;
  card: Partial<VehicleData>;
  modes: Record<GameMode, Partial<VehicleData>>;
}

export interface GameCatalog {
  version: string;
  vehicles: GameVehicle[];
}

let catalog: Promise<GameCatalog> | null = null;

export function loadGameCatalog(): Promise<GameCatalog> {
  catalog ??= fetch('assets/game/vehicles.json').then((r) => {
    if (!r.ok) throw new Error(`vehicles.json: HTTP ${r.status}`);
    return r.json();
  });
  catalog.catch(() => (catalog = null));
  return catalog;
}

export function gameToVehicle(g: GameVehicle, mode: GameMode, version: string): VehicleData {
  return {
    dataFreshness: 'verified_current',
    freshnessNote: `Game files ${version}`,
    cardLayout: 'modern',
    flagBackdropOpacity: 1,
    flagBackdropScale: 1,
    talisman: false,
    topCrewStar: true,
    headerTooltip: 'The information window can be closed with a mouse click.',
    protectionSummary: '',
    bulletproofRating: '',
    systems: '',
    visibility: '',
    gameMode: mode,
    ...g.card,
    ...g.modes[mode],
  } as VehicleData;
}
